### ISSUE TITLE
Add transaction interfaces meta_state_service

### ISSUE THREAD

**Issue by shengofsun** [imzhenyu/rDSN#146]
In order to make create/drop table easy, I want to add transaction interface to the meta_state_service, which can make use of the batch-transaction APIs in zookeeper. But this interface isn't universal enough because a meta_state_service provider  may not support the transaction sematics.
I've added the interfaces on my own branchs and I need your advices @imzhenyu .
You can view the interfaces [here](https://github.com/shengofsun/rDSN/blob/table_api/include/dsn/dist/meta_state_service.h)

**Comment by imzhenyu** [comment]
Hi @shengofsun , I think this is nice and important interface. However, I do have some issues with your interface.

class transaction_entries { 
71             public: 
72                 virtual ~transaction_entries() {} 
73                 virtual bool create_node(const std::string& node, const blob& value = blob()) { return false; } 
74                 virtual bool delete_node(const std::string& node) { return false; } 
75                 virtual bool set_data(const std::string& node, const blob& value = blob()) { return false; } 
76             };

/\* 
90              \* submit transaction, it should be all succeeded or all failed 
91              \* cb_code: the task code specifies where to execute the callback 
92              \* cb_transaction: callback, ec to indicate success or failure reason 
93              \* tracker: to track (wait/cancel) whether the callback is executed 
94              _/ 
95             virtual task_ptr submit_transaction(const std::shared_ptr<transaction_entries>& entries, 
96                                       task_code cb_code, 
97                                       const err_callback& cb_transaction, 
98                                       clientlet_ tracker = nullptr) = 0;

My understanding about the transaction_entries is that they are provided by the caller of the meta state service, and they should only describe what I want meta state service do for me, instead of how the meta state service should do them. Therefore, the virtual functions of transaction-entries are kinds of confusing for me. Would you mind elaborating the usage more clearly so it may help me understand better of your proposal. Thx.

**Comment by shengofsun** [comment]
[Here](https://github.com/shengofsun/rDSN/commit/579713f9a24b32ebc4171573c00dcf162fcfcca5) is my commits. In the bottom of this page is the test code on the interfaces, and you can take it as a sample :)

The providers may have different data structures for a transaction operation, so we may avoid memory copy if we let providers implement the transaction_entries. Taking the retrying logic into account, I think this optimization is necessary.

**Comment by imzhenyu** [comment]
This actually introduces extra dependencies between the caller and the providers, besides the base interface. In other words, we cannot easily switch to another provider (e.g., etcd-based). This is against one of the major goal in rDSN - things can be developed independently, and they can be integrated seamlessly. I strongly recommend you to remove such dependency and provide general transaction entries that do not depend on the implementation of certain providers. I understand that you may lose certain optimization opportunities, but code modularity is almost always the first priority. Thx.

**Comment by qinzuoyan** [comment]
@imzhenyu , I think make trans_entries managed by provider implement is acceptable, and will not break code modularity. When using it, user first call new_entries() to create container, then add operators into container, and then call submit_transaction() to submit it. Using internal created container and using shared_ptr to hold the lifetime will make the interface easy to use, and get better performance (avoid unnecessary memory copy), and make retry easier (reuse the container to retry).

If you switch the provider, the new_entries() would also witch and return a proper container. I think users would not call interfaces across different providers.

**Comment by imzhenyu** [comment]
My bad - I did not see that new_entries are also part of the bas interface - that's why I feel weird in the first place. In that case, I think it is ok. A nit is to rename new_entries to new_transaction_entries. Sorry for my being careless when going through the code.

**Comment by qinzuoyan** [comment]
Ok, let's go on

**Comment by shengofsun** [comment]
Ok, I will rename it next pr :)
