### ISSUE TITLE
upgrade to C++14

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#195]
Hi there,

Per discussion with the others (esp. Tianyi), we are proposing to upgrade our base requirement from C++ 11 to C++ 14. The reason is to avoid certain performance overhead due to the missing features in C++ 11 (e.g., capture and move). This issue request aims at collecting all the necessary changes and possible upsides/downsides of this upgrade, so we can have a smooth one-shot action later. 

Thanks,
Zhenyu

**Comment by imzhenyu** [comment]
Here is the least changes in my mind:
(1) appveyor 
(2) build script for windows
(3) wiki for stating our base requirement for adoption

**Comment by glglwty** [comment]
The most needed feature in my mind is generalized lambda capture, which has been supported since gcc4.5, clang 3.4 or VS2015. 

### why generalized lambda capture

We have a lot of callback-managed-lifetime patterns in our code. For example in mutation_log.cpp:

``` c++
    _issued_write_task = _current_log_file->commit_log_block(
        *_pending_write,
        start_offset,
        code,
        this,
        std::bind(
            &mutation_log::internal_write_callback, this,
            std::placeholders::_1,
            std::placeholders::_2,
            _current_log_file,
            _pending_write,
            _pending_write_callbacks,
            _pending_write_max_commit),
        -1
        );
```

Here `_pending_write_callbacks` would be immediately dropped when the std::bind object is dropped. In order to ensure its lifetime we have pass shared_ptr to the bind object. It actually copies the `shard_ptr` and would invoke 2 unnecessary reference counter operations.
What we need is to pass the ownership of `_pending_write_callbacks` to the closure, so we only need a `unique_ptr` here. But we have to move it into the closure, which needs the support of c++14.

Sometimes not capturing objects by move has worse aftermath than several atomic operations. You might allocate memory when you copy it. Failing to move `std::function` is pervasive in our code. Here's an example in `clientlet.h`:

``` c++
template<typename TResponse>
            inline task_ptr create_rpc_call(
                dsn_message_t msg,
                std::function<void(error_code, const TResponse&, void*)>& callback,
                void* context,
                int reply_hash,
                clientlet* owner
                )
            {
                if (callback != nullptr)
                {
                    rpc_reply_handler cb = std::bind(
                        &on_rpc_response4<
                        TResponse,
                        std::function<void(::dsn::error_code, const TResponse&, void*)>
                        >,
                        callback,
                        context,
                        std::placeholders::_1,
                        std::placeholders::_2,
                        std::placeholders::_3
                        );

                    task_ptr task = new safe_task<rpc_reply_handler>(cb);

                    task->add_ref(); // released in exec_rpc_response
                    auto t = dsn_rpc_create_response_task_ex(
                        msg,
                        safe_task<rpc_reply_handler >::exec_rpc_response,
                        safe_task<rpc_reply_handler >::on_cancel,
                        (void*)task,
                        reply_hash,
                        owner ? owner->tracker() : nullptr
                        );
                    task->set_task_info(t);
                    return task;
                }
                else
                {
                    return create_empty_rpc_call(msg, reply_hash);
                }
            }
        }
```

The problem is same but more subtle here. In `std::bind` we are not only copying the `std::function` but also invoking `malloc`! Actually in our eon layer a lambda expression might be boxed into `std::function` and copied for more than 2 times. Every boxing and copy operation would involve mallocing.

The right way to do this is actually passing callbacks as generic parameters in C++lib, moving a lambda into another lambda when you need some sort of combination, and box it (into something like `safe_task_handle`) at the interface of C API --- we have to do it once somewhere. In this process move-capture is also needed.

### alternatives

No, there isn't one.

**Comment by imzhenyu** [comment]
@glglwty you may share certain links about these interesting features so others like me not familiar with that can know.

**Comment by qinzuoyan** [comment]
Looks amazing. How can you know so many things, @glglwty ?
But I think we should firstly release a stable version, and these optimizations are not so argent.
From our initial testing, the performance is good enough. So I think the current most important thing is to provide a usable and stable system to our users. Many people are looking forward to use our system in XiaoMi.

**Comment by glglwty** [comment]
@qinzuoyan I'm just optimizing around RPC performance. I did profiling for empty RPC call and found that many unnecessary allocation actually happens in our EON layer. Creating a task takes one `malloc` in ZION (new task_c) but uncountable `malloc`s in EON. Optimizing std::function stuff should eliminate some of them and C++14 is a necessary tool.

What we concern is the actual GCC version you use in production. If it's higher than 4.5 then we are all set and I would begin refactoring. If you are using 4.9 or higher we can use most of C++14 features, but other features are far less important than this one. I'm just trying to explain why generalized lambda is essential.

**Comment by glglwty** [comment]
By the way, I'm interested in the performance result you get. Can we have a copy of it? A "good enough performance" is an exciting news for me!

**Comment by qinzuoyan** [comment]
OK, I'll append the result to #54

**Comment by imzhenyu** [comment]
Great. I don't see objections so far. I will start the upgrade now.

**Comment by imzhenyu** [comment]
Done.
