### ISSUE TITLE
raw-medal deployment using minos 

### ISSUE THREAD

**Issue by imzhenyu** [imzhenyu/rDSN#29]
TODO

**Comment by goksyli** [comment]
@shengofsun I need some materials for deployment using `minos`. Could you send me some via email if convenient.

**Comment by qinzuoyan** [comment]
Minos github: https://github.com/xiaomi/minos
Any questions, @xiaotz is here.

**Comment by xiaotz** [comment]
@goksyli 

https://github.com/xiaomi/minos/wiki
you can start from it.

However, I did not deploy the minos myself. in addition, I change some code in our internal code branch.

I can own this issue since we have minos experts in our corp.
and I will give you a detailed document about deployment.

what do you think?

**Comment by goksyli** [comment]
I have to deploy `rDSN` using `minos` at `Microsoft` and I think having a detailed document about deployment is a good choice.

**Comment by imzhenyu** [comment]
Great. @goksyli let's focus the two other approaches then, and do this one later after @xiaotz finalizes a detailed doc using minos. @xiaotz, since we want to have a running bed asap, this is kinds of urgent. Thanks.

**Comment by goksyli** [comment]
@imzhenyu, Ok I got the message.

**Comment by xiaotz** [comment]
@goksyli @imzhenyu  sure

I will finish this work ASAP. 
ETA is Dec. 15

**Comment by imzhenyu** [comment]
As discussed in email, this approach is infeasible for the time being. Close now.
