### ISSUE TITLE
serialized json str with thrift is hard to read

### ISSUE THREAD

**Issue by shengofsun** [imzhenyu/rDSN#397]
The following is a "partition_configuration" structure generated by thrift's json protocol: 
"{"0":{"rec":{"1":{"rec":1},"2":{"i64":0},"3":{"i32":3},"4":{"rec":0},"5":{"lst":["rec",0]},"6":{"lst":["rec",0]},"7":{"i64":0}}}}".

As we all know we want json to help us to debug our system, but I think messages like may be useless.

Besides, the json format is not consistent with the old ones generated by @glglwty 's "json_helper", which means that we can't easily upgrade meta server to the new version for the running service in xiaomi.

How about continuing to use the old json generator? Or is there anyone who knows something about the protobuf's json generator? @imzhenyu @glglwty @ykwd

**Comment by mcfatealan** [comment]
hi @shengofsun , Zhenyu is away and back to his hometown this week, and so maybe he is not so active these days.

For your concern, I'm not sure if I correctly got your idea, if you want to view structure section name in message, it's not necessary because you can always view these info in the the unmarshalled result. Tianyi's encoder is actually intended for CLI command but not RPC requests. For your example, if I'm using JavaScript client with codegen library, I new a `partition_configuration` and use the received RPC message to initialize it,  then `JSON.stringify` it, you can get what you want.

**Comment by shengofsun** [comment]
@mcfatealan If you use the thrift's encoder just for rpc, why not use binary format or native call to C++ serialization method of rDSN, which is more sufficient. 
The reason why I concern about the json thing is that data of meta server stored on zookeeper is using json. In current code base, the json stored on meta is also generated by thrift, which is inconsistent with the earlier version, and which make it not easy when we want to check meta's information from zookeeper.

**Comment by imzhenyu** [comment]
Thanks Chang and Weijie. @shengofsun the previous refactor done by @ykwd is mostly to support multiple formats at the same time for the RPC handlers - i.e., you can register new request/response marshall/unmarshall formats, such as a new "standard json format". On the other hand, the thrift json format does not take the field name but their index as the json key, which I think is most for compatibility support across multiple versions. There are pros and cons for using thrift-json or adding a new "standard json" format. It is great if you want to adopt the latter approach, and the only concern for me is that if we do this, let's do it completely for both encoding/decoding :-) What do you think?

**Comment by shengofsun** [comment]
json state stored in meta state service have been replaced by standard json.
