### ISSUE TITLE
fix rep_test to make it work ok, and put it into hook checks

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#41]

**Comment by qinzuoyan** [comment]
All fixed except case-402, which has been move to directory "to-fix".
Now that the rep_tests often fail, currently we disable it util someday the system becomes stable.

**Comment by imzhenyu** [comment]
You mean case-402 often fails, or there are also other cases failing sometimes as well? I think one thing we need to pay attention is the capability of our current act test, which only supports total order of events but not partial order. We therefore need to make sure we only setup events with total order in our test cases. Otherwise, depends on the runtime scheduling, the cases may or may not fail in test.

**Comment by qinzuoyan** [comment]
Case-402 always fail, and I have not found out the reason.
We can improve the cases to make them run with total order, but it's also necessary to add partial order support, when I have free time.

**Comment by imzhenyu** [comment]
Great, and it is best if the further refinement can target a broader range of applications. I think the act framework has the potential to be a great general tool for many rDSN applications in the end.

**Comment by qinzuoyan** [comment]
I have found the reason for case-402 failure: in replica::update_local_configuration(), the returned mutation_ptr of check_possible_work() is not properly handled, so the mutation is discarded, and the write operation is failed.
I have fixed it in pr https://github.com/imzhenyu/rDSN/pull/145

**Comment by imzhenyu** [comment]
my bad and nice catch. Guoxi also reports that there are timeouts in the end even without fault injection, now we know why.
