### ISSUE TITLE
zookeeper config specification

### ISSUE THREAD

**Issue by qinzuoyan** [imzhenyu/rDSN#46]
Now there are two services which have zookeeper implements, they are:
- meta_state_service, implemented by meta_state_service_zookeeper
- distributed_lock_service, implemented by distributed_lock_service_zookeeper

Zookeeper sessions are controlled by zookeeper_session_mgr, which is a **_singleton object**_. General zookeeper configs can be set in **_[zookeeper]**_ section, such as hosts_list, timeout, etc. Currently, all service nodes in one process share the same zookeeper config, but in the future, if we need different zookeeper configs for different service nodes, then we can extend the config, for example, add config section **_[zookeeper.${app_name}]**_ for special app.

For meta_state_service, the interface semantic is obvious: the "node" parameter of each method is the full path of node. If we need some special configs for the implement, we can set config in section **_[${service_implement_name}]**_, for example, section **_[meta_state_service_zookeeper]**_ for implement meta_state_service_zookeeper.

For distributed_lock_service, it's more complicated. Each methods need a "lock_id" parameter. If the "lock_id" parameter is expected to a full path, just like meta_state_service, there is no problem. But we should assume that the lock service is built on a tree namespace, that is, the "lock_id" may be any unique key (not limited to path), such as number, string, etc. But to zookeeper implementation, we should map the lock id to a node path. Currently, we read config **_[meta_server].cluster_root**_ as the path prefix, and the lock node path is "${cluster_root}/lock/${lock_id}". Actually, it may be more proper to set path prefix in a specific config section, or pass from initialize parameter, or even we can acquire that the lock_id should be a full path, just like meta_state_service. **_We need discuss it.**_

**Comment by qinzuoyan** [comment]
@imzhenyu , let's discuss the problem above.

**Comment by imzhenyu** [comment]
Thanks, @qinzuoyan. I think this is great and I agree most of them. My comment is to decouple the state and execution of different apps when they are in the same process, otherwise this may cause different tasks and locks etc. from different node interacting with each, which is not exactly the case in the real deployment, and may cause mal-functioning of the simulator. On the other hand, since we won't have multiple apps in the same process in real deployment, this won't cause performance lost. [not exactly true, but should be the common case] This requires a per-node zookeeper session manager, and you can set it up in app::start, and pass its address to the other services that rely on this session manager. For naming hierarchy, I think any case is good enough as long as we have a fixed convention. For example, ${cluster_root}/[${app_name}/]$[service}/${state}. How do you think about this?

**Comment by shengofsun** [comment]
In my opinion, what we need is a per-node zookeeper session instead of a per-node zookeeper session mgr. Currently, each service_node has a zookeeper session, and different sessions have different zookeeper threads. As for zookeeper session mgr, it's only a map which manage all the (app, session) pairs.

**Comment by imzhenyu** [comment]
This is even better - we do only have one zookeeper session in each node. The cross-node map is however, not good for rdsn's model. After all, we assume network is the only resource that different nodes can share. Violation of this assumption brings problems, e.g., what node the lock that protect this map belongs to?

**Comment by qinzuoyan** [comment]
Another pull request is created: https://github.com/imzhenyu/rDSN/pull/67.
I choose to passing lock_root to distributed_lock_service **_by initialize parameters**_, but not by setting in config, which I think would be more flexible. Then the lock node path will be "${lock_root}/${lock_id}", and children will be ephemeral and sequence nodes of "${lock_root}/${lock_id}/${LOCK_NODE_PREFIX}${i}".

For the cross-node problem, we are seeking for a better way.

**Comment by qinzuoyan** [comment]
There are more discussions in https://github.com/imzhenyu/rDSN/pull/67#discussion_r47324520, mark here.

**Comment by qinzuoyan** [comment]
now the zookeeper config is like:

```
[meta_server]
cluster_root = /test/testcluster
meta_state_service_type = meta_state_service_zookeeper
meta_state_service_parameters = 
distributed_lock_service_type = distributed_lock_service_zookeeper
distributed_lock_service_parameters = /test/testcluster/lock
```
