### ISSUE TITLE
the problem with project "dsn.nfs.test"

### ISSUE THREAD

**Issue by wangyan32** [imzhenyu/rDSN#69]
when i wanna try the nfs test in dsn, i found the example of nfs is not work well. In "nfs_test.main.cpp", the code "#include "nfs_test.app.example.h"" at the front will case endless loop, and can not drop in the main function. I use the code in a wrong way? or some others? thank you!

**Comment by imzhenyu** [comment]
i'm looking into this now.

**Comment by imzhenyu** [comment]
@wangyan32, dsn.nfs.test is currently a service instead of one-pass execution, inside which the client app periodically copies file ./dsn.nfs.test from server to its local ./dst dir. And you can see dsn_run("config.ini", true) in main, which means after call dsn_run, the main threads enters a sleep mode, which never exits.

If you want to have a one-time tool copies file for you, I don't think our nfs is a good fit, you can simply use scp on Linux, or xcopy on windows. Nfs in rdsn is more like a FTP server, which never ends. 

Hope this helps.
